wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  power_save_mode: light
# indien een fall back noodzakelijk is verwijder de #
#  ap:
#    ssid: "${name}"
#    password: !secret ap_password
#    ap_timeout: 15s

captive_portal:

text_sensor:
  - platform: wifi_info
    ip_address:
      name: ${esp_ip}
      icon: mdi:ip
    ssid:
      name: ${esp_ssid}
      icon: mdi:wifi
    bssid:
      name: "WiFi BSSID"
      icon: mdi:router-wireless

sensor:
  - platform: wifi_signal
    name: ${wifi_signal_db}
    id: wifi_signal_db
    update_interval: 5s
    entity_category: diagnostic
  - platform: copy
    source_id: wifi_signal_db
    name: ${wifi_signal_proc}
    id: wifi_signal_strength_percent
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: diagnostic
    device_class: signal_strength
    icon: mdi:wifi
