#### ABB B23 3phase kWh Meter ####

modbus_controller:
  - id: B23
    address: 3
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 30s
    command_throttle: 350ms  # voorkomt overbelasting bij meerdere sensors
    #timeout: 400ms  # optioneel, alleen nodig bij trage apparaten

    ## change parity frome even to none on the ABB B23 meter

## 1 Total Energy (kWh) B23
  - platform: modbus_controller
    modbus_controller_id: B23
    name: "B23 Import energy total"
    address: 0x5000
    register_type: holding
    value_type: U_QWORD
    device_class: "energy"
    unit_of_measurement: "kWh"
    accuracy_decimals: 2
    state_class: "total_increasing"
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: B23
    name: "B23 Export energy total"
    address: 0x5004
    register_type: holding
    value_type: U_QWORD
    device_class: energy
    unit_of_measurement: "kWh"
    accuracy_decimals: 2
    state_class: "total_increasing"
    filters:
      - multiply: 0.01

## 2 Total energy per phase
## Active import energy (kWh) B23
  - platform: modbus_controller
    modbus_controller_id: B23
    name: "B23 Import energy L1"
    address: 0x5460
    register_type: holding
    value_type: U_QWORD
    device_class: energy
    unit_of_measurement: "kWh"
    accuracy_decimals: 2
    state_class: "total_increasing"
    filters:
      - multiply: 0.01
      - lambda: |-
          static float last_value = NAN;
          const float min_val = 0.0;  // Minimale onderwaarde
          const float max_increase = 1000.0;  // Maximale toename per update (pas dit aan)
          if (isnan(last_value)) {
            last_value = x;
          }
          if (x < last_value || (x - last_value) > max_increase) {
            return last_value;  // Gebruik de vorige waarde als de nieuwe waarde onwaarschijnlijk is
          } else {
            last_value = x;  // Update de laatste waarde
            return x;
          }
      
  - platform: modbus_controller
    modbus_controller_id: B23
    name: "B23 Import energy L2"
    address: 0x5464
    register_type: holding
    value_type: U_QWORD
    device_class: energy
    unit_of_measurement: "kWh"
    accuracy_decimals: 2
    state_class: "total_increasing"
    filters:
      - multiply: 0.01
      - lambda: |-
          static float last_value = NAN;
          const float min_val = 0.0;  // Minimale onderwaarde
          const float max_increase = 1000.0;  // Maximale toename per update (pas dit aan)
          if (isnan(last_value)) {
            last_value = x;
          }
          if (x < last_value || (x - last_value) > max_increase) {
            return last_value;  // Gebruik de vorige waarde als de nieuwe waarde onwaarschijnlijk is
          } else {
            last_value = x;  // Update de laatste waarde
            return x;
          }

  - platform: modbus_controller
    modbus_controller_id: B23
    name: "B23 Import energy L3"
    address: 0x5468
    register_type: holding
    value_type: U_QWORD
    device_class: energy
    unit_of_measurement: "kWh"
    accuracy_decimals: 2
    state_class: "total_increasing"
    filters:
      - multiply: 0.01
      - lambda: |-
          static float last_value = NAN;
          const float min_val = 0.0;  // Minimale onderwaarde
          const float max_increase = 1000.0;  // Maximale toename per update (pas dit aan)
          if (isnan(last_value)) {
            last_value = x;
          }
          if (x < last_value || (x - last_value) > max_increase) {
            return last_value;  // Gebruik de vorige waarde als de nieuwe waarde onwaarschijnlijk is
          } else {
            last_value = x;  // Update de laatste waarde
            return x;
          }

## Active export energy (kWh) B23
  - platform: modbus_controller
    modbus_controller_id: B23
    name: "B23 Export energy L1"
    address: 0x546C
    register_type: holding
    value_type: U_QWORD
    device_class: energy
    unit_of_measurement: "kWh"
    accuracy_decimals: 2
    state_class: "total_increasing"
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: B23
    name: "B23 Export energy L2"
    address: 0x5470
    register_type: holding
    value_type: U_QWORD
    device_class: energy
    unit_of_measurement: "kWh"
    accuracy_decimals: 2
    state_class: "total_increasing"
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: B23
    name: "B23 Export energy L3"
    address: 0x5474
    register_type: holding
    value_type: U_QWORD
    device_class: energy
    unit_of_measurement: "kWh"
    accuracy_decimals: 2
    state_class: "total_increasing"
    filters:
      - multiply: 0.01

## 3 Instantaneous values
## 3.1 Voltage (V) B23
  - platform: modbus_controller
    modbus_controller_id: B23
    name: "B23 Voltage L1-N"
    address: 0x5B00
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 1
    device_class: voltage
    unit_of_measurement: "V"
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: B23
    name: "B23 Voltage L2-N"
    address: 0x5B02
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 1
    device_class: voltage
    unit_of_measurement: "V"
    filters:
      - multiply: 0.1
  - platform: modbus_controller
    modbus_controller_id: B23
    name: "B23 Voltage L3-N"
    address: 0x5B04
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 1
    device_class: voltage
    unit_of_measurement: "V"
    filters:
      - multiply: 0.1

## 3.2 Current (A) B23
  - platform: modbus_controller
    modbus_controller_id: B23
    name: "B23 Current L1"
    address: 0x5B0C
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 2
    device_class: current
    unit_of_measurement: "A"
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: B23
    name: "B23 Current L2"
    address: 0x5B0E
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 2
    device_class: current
    unit_of_measurement: "A"
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: B23
    name: "B23 Current L3"
    address: 0x5B10
    register_type: holding
    value_type: U_DWORD
    accuracy_decimals: 2
    device_class: current
    unit_of_measurement: "A"
    filters:
      - multiply: 0.01

## 3.3 Active Power (Watt) B23
  - platform: modbus_controller
    modbus_controller_id: B23
    name: "B23 Power total"
    address: 0x5B14
    register_type: holding
    value_type: S_DWORD
    accuracy_decimals: 2
    device_class: power
    unit_of_measurement: "W"
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: B23
    name: "B23 Power L1"
    address: 0x5B16
    register_type: holding
    value_type: S_DWORD
    accuracy_decimals: 2
    device_class: power
    unit_of_measurement: "W"
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: B23
    name: "B23 Power L2"
    address: 0x5B18
    register_type: holding
    value_type: S_DWORD
    accuracy_decimals: 2
    device_class: power
    unit_of_measurement: "W"
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: B23
    name: "B23 Power L3"
    address: 0x5B1A
    register_type: holding
    value_type: S_DWORD
    accuracy_decimals: 2
    device_class: power
    unit_of_measurement: "W"
    filters:
      - multiply: 0.01

## 3.4 Frequency (Hz) B23
  - platform: modbus_controller
    modbus_controller_id: B23
    name: "B23 Frequency"
    address: 0x5B2C
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 2
    device_class: frequency
    unit_of_measurement: "Hz"
    filters:
      - multiply: 0.01

## 3.5 Power factor (-) B23
  - platform: modbus_controller
    modbus_controller_id: B23
    name: "B23 Power factor total"
    address: 0x5B3A
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 3
    device_class: power_factor
    filters:
      - multiply: 0.001
