#### ABB B23 3phase kWh Meter ####

modbus_controller:
  - id: B23
    address: 3
    modbus_id: modbus1
    setup_priority: -10
    update_interval: 30s
    command_throttle: 350ms  # voorkomt overbelasting bij meerdere sensors
    #timeout: 400ms  # optioneel, alleen nodig bij trage apparaten

    ## change parity frome even to none on the ABB B23 meter

sensor:
#testsensor
- platform: modbus_controller
  modbus_controller_id: B23
  name: "B23 Test Voltage L1"
  address: 0x5000
  register_type: holding
  value_type: U_DWORD

